In [2]:
#########-------NumPy Indexing and Selection---------###########

In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5] #slicing notation

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
#to get everything upto index 6

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr [5:] #to get everything upto end starting from given point

array([ 5,  6,  7,  8,  9, 10])

In [12]:
#a normal Python list is different from arrays, 
#bcz of array's ability to broadcast

In [13]:
arr[0:5] =100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [15]:
arr = np.arange(0,11)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_arr = arr[0:6]

In [18]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:]= 99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy = arr.copy()

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [27]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_copy[:]=100

In [29]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [30]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [31]:
#to avoide this typr of repetition, another comand arr_copy()
#is used here...

In [32]:
#####------------creating a 2D Array ----------###############

In [34]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [35]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [37]:
#Two general formats for grabbing elements from 2d array or matrix
#1st..There is double bracket format
#2nd..there is single bracket format with comma

In [38]:
arr_2d[0]

array([ 5, 10, 15])

In [39]:
arr_2d[0][0] #double bracket notation

5

In [42]:
arr_2d[1][0] # #double bracket notation

20

In [41]:
arr_2d[2][2]  #double bracket notation

45

In [43]:
# now using comma single bracket notation

In [44]:
arr_2d[2,1]

40

In [45]:
arr_2d[0,2]

15

In [46]:
arr_2d[1,2]

30

In [48]:
# ...........now to grab sub matrices from a matrix...........
#or to grab certain section of the entire matrix

In [53]:
arr_2d[:2, :2]

array([[ 5, 10],
       [20, 25]])

In [54]:
arr_2d[0:,0:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [55]:
arr_2d[0:, 1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [56]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [57]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [58]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [60]:
arr_2d[1:3]

array([[20, 25, 30],
       [35, 40, 45]])

In [61]:
######------------_Conditional Selection------------###########

In [62]:
arr = np.arange(1,11)

In [63]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
bool_arr = arr > 5

In [66]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [68]:
arr[bool_arr] #so here conditional statement is applying
#it will return only the true values

array([ 6,  7,  8,  9, 10])

In [69]:
arr[arr>5]  #syntax notation going to be used as 
#far as conditional selection

array([ 6,  7,  8,  9, 10])

In [79]:
arr_new_2d = np.arange(50).reshape(5,10)

In [80]:
arr_new_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [83]:
arr_new_2d[1:3, 3:5 ]

array([[13, 14],
       [23, 24]])