In [1]:
#conda install numpy

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(0,11,2) #to get even numbers, by adding step size

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))#by adding tuples of dimensions

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.zeros((2,3))
#two dimensional arrays, clear from two brackets[[]]

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [18]:
np.linspace(0,5,100) 
#it looks l;ike two dimnsional, but it is one dim.
# its a one dimensional array as one bracket [] is there 

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [19]:
#arange: in this third argument is the step size.


#linspace: in this third argument is the number of points we need.

In [20]:
#creating identity matrix using numPy
#identity matrix means no of rows and columns are equal
# diagonal elemnets are 1 and others are all zeros
#useful in linear algebra problems

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [24]:
#Few ways to create arrays of random numbers

In [25]:
######-------------rand method -------------#####

In [26]:
np.random.rand(5)
#using rand is going to create an array of the given shape you pass in
#single digit to get back one dimensional array
#from 0 to 1 , any five ..

array([0.58218776, 0.21117692, 0.12637009, 0.98757278, 0.6743819 ])

In [27]:
np.random.rand(5,5)
#to get two dimensioanl, unlike passing the tupleslike(()), just pass in
#the dimensions as separate arguments using()
#

array([[0.78524733, 0.62889464, 0.03470802, 0.23060739, 0.10060745],
       [0.77825206, 0.73742973, 0.19488522, 0.12598895, 0.85408073],
       [0.19596058, 0.60177967, 0.89385296, 0.6998209 , 0.06057199],
       [0.41283505, 0.30708739, 0.45085858, 0.12991582, 0.01041625],
       [0.13168488, 0.45674687, 0.18866554, 0.52615275, 0.82066895]])

In [28]:
######-------------rand n method -------------#####

In [29]:
#if we want to return a sample or many samples from the standard
#normal distribution or a Gaussian distribution, instead of using 
#rand, we will use 'rand n' here

In [30]:
np.random.randn(2)
#it will return numbers not from distribution 0 to 1 but instead
#from a standard normal distribution centre around zero.

array([-1.06655816, -1.99774805])

In [31]:
# so for two dimensions, just passing two variables

In [32]:
np.random.randn(4,4)

array([[ 0.05900705, -0.09856814, -3.49937531, -0.32720688],
       [-0.36069552,  0.67882676, -0.41027655, -0.40771803],
       [-1.19706765,  1.14934701, -0.22744174,  0.09336043],
       [ 1.19751491, -0.21482092,  0.23334325,  0.29936042]])

In [33]:
######-------------randint method -------------#####

In [34]:
# next method to get random numbers is 'rand int'. it returns
# random integers from a low to high number 
#inclusive of the low number but exclusive of high number
#(1,100), 1 is included but 100 not

In [35]:
np.random.randint(1,100)

72

In [36]:
np.random.randint(1,100,10)

array([14,  5, 12, 91, 49, 61, 71, 23, 54, 75])

In [37]:
arr = np.arange(25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [39]:
ranarr = np.random.randint(0,50,10)

In [40]:
ranarr

array([39, 30, 41, 40,  6, 20,  5,  3,  7,  2])

In [41]:
######-------------reshape method -------------#####

In [42]:
#reshape method is f=going to return an array containing the 
#same data of a new shape

In [43]:
arr.reshape(5,5)
#here in 'arr' defined above have only 25 elements.
#so to reshape command will be 5X5 only.
# to get more (5,10), 50 elements should be there.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
#arr.reshape(4,4)
#for this as well, error is there

In [45]:
#########--------Max, Min or index location-------------_########

In [46]:
ranarr.max()

41

In [47]:
ranarr.min()

2

In [48]:
ranarr

array([39, 30, 41, 40,  6, 20,  5,  3,  7,  2])

In [49]:
#location of max or min value by specifying our max or min
#meaning what index value is this max or min value is

In [50]:
ranarr.argmax()

2

In [51]:
ranarr.argmin()

9

In [52]:
######------To figure out the shape of a vector----------#######

In [53]:
arr.shape

(25,)

In [54]:
#here (25,) means that array, 'arr' is just a one dimensional

In [55]:
# to change it into a two dimensional....

In [56]:
arr = arr.reshape(5,5)

In [57]:
arr.shape

(5, 5)

In [58]:
arr.dtype

dtype('int64')

In [59]:
#'dtype' shows the data type..here it is 64bit integers....


In [60]:
#if we don't want to type np.random.rand, then use following command

In [61]:
from numpy.random import randint

In [62]:
randint(2,6)

2